### ISSUE TITLE
stripe-buffer occasionally leaves `cursor-type` as `nil` in all buffers

### ISSUE THREAD

**Issue by kcandrews** [sabof/stripe-buffer#11]
Sometimes after leaving dired I find that I no longer have a cursor (especially as I rarely shutdown emacs). I can get it back by resetting the `cursor-type`.  Maybe you can use setq-local to keep the changes in cursor local to the buffer?

**Comment by sabof** [comment]
Does `M-x describe-variable RET cursor-type RET` mention "Automatically becomes buffer-local when set."? What is your Emacs version?

**Comment by kcandrews** [comment]
It does say that and I'm using Emacs 24.4.

```
cursor-type is a variable defined in `C source code'.
Its value is hbar
Original value was t

  Automatically becomes buffer-local when set.
```

I changed the three lines:

```
<   (setq-local cursor-type nil)
---
>   (setq cursor-type nil)
334c334
<     (setq-local cursor-type t)))
---
>     (setq cursor-type t)))
341c341
<     (setq-local cursor-type nil)))
---
>     (setq cursor-type nil)))
```

And will play around with that and see if it fixes the issue. But as you say, it should be buffer-local...

**Comment by sabof** [comment]
Might it be possible that some other code is responsible? Perhaps it takes the value of the cursor set by stripe-buffer, changes the cursor (or thinks it might have changed it), and then does `setq-default` assuming that `nil` was the user's default cursor?

**Comment by kcandrews** [comment]
I'm using `switch-window.el` to navigate my frame and it does exactly what you describe.
