### ISSUE TITLE
call-interactively: Wrong number of arguments: #[(stripe-regexp &optional stripe-line-interval buffer) "

### ISSUE THREAD

**Issue by ypitomets** [sabof/stripe-buffer#2]

**Comment by sabof** [comment]
Try upgrading, and see if the issue persists - neither stripe-regexp, nor stripe-line-interval are mentioned in the current version.

**Comment by ypitomets** [comment]
After deleting *.elc :
call-interactively: Wrong number of arguments: (lambda (stripe-regexp &optional stripe-line-interval buffer) "Make turn on stripe line with BUFFER.
`stripe-regexp' is match string per line.
`stripe-line-interval' is interval lines that need match." (interactive) (or stripe-line-interval (setq stripe-line-interval 1)) (or buffer (setq buffer (current-buffer))) (stripe-buffer-off buffer) (save-current-buffer (set-buffer buffer) (save-excursion (let (overlay end-point) (goto-char (point-min)) (while (not (eobp)) (beginning-of-line) (if (search-forward-regexp stripe-regexp (line-end-position) t) (progn (setq overlay (make-overlay (match-beginning 0) (match-end 0))) (overlay-put overlay (quote face) stripe-highlight-face) (setq stripe-highlight-overlays (cons overlay stripe-highlight-overlays)))) (forward-line stripe-line-interval)))))), 0

**Comment by sabof** [comment]
You have an old version. Try using this one: https://raw.github.com/sabof/stripe-buffer/master/stripe-buffer.el

**Comment by ypitomets** [comment]
Sorry, I installed old version from emacswiki via el-get. All work fine after updating el-get-sources, thanks!
