### ISSUE TITLE
Looks ugly with solarized theme

### ISSUE THREAD

**Issue by jaseemabid** [sabof/stripe-buffer#5]
Attaching sample screenshots  with and without mode enabled. 

![2013-05-05-205356_1366x768_scrot](https://f.cloud.github.com/assets/601714/463796/45a9084e-b59e-11e2-9892-5c5e39bd3135.png)

![2013-05-05-205404_1366x768_scrot](https://f.cloud.github.com/assets/601714/463797/4607548a-b59e-11e2-8f8a-03177ef7864e.png)

**Comment by sabof** [comment]
It's not meant to adjust to every theme -- you need to pick a color yourself. `M-x customize-face RET stripe-highlight`
