### ISSUE TITLE
image-dired-dired-toggle-marked-thumbs don't work correctly

### ISSUE THREAD

**Issue by myuhe** [sabof/stripe-buffer#6]
Reproduce:
1. M-x turn-on-stripe-buffer-mode on dired.
2. On line that  overlay stripe-highlight-face , M-x image-dired-dired-toggle-marked-thumbs.
3. Inline image don't show. :(

**Comment by sabof** [comment]
I've added an advice that will turn stripe-buffer off in such cases.

image-dired-dired-toggle-marked-thumbs assumes that it's the only mode that uses overlays. Fixing that is beyond the scope of this package.

**Comment by sabof** [comment]
Actually I can't push on github for some reason.

**Comment by sabof** [comment]
Done

**Comment by myuhe** [comment]
@sabof 

Confirmed.

When image-dired-dired-toggle-marked-thumbs is executed , stripe-buffer-mode leaves turn off.
I think when inline image is disabled  stripe-buffer-mode should turn on.

**Comment by sabof** [comment]
There is no clean way to do that. If you wish you can submit a bug report at bug-gnu-emacs@gnu.org, regarding this function and the assumptions it makes.

**Comment by sabof** [comment]
The original problem with `image-dired-dired-toggle-marked-thumbs` was fixed on emacs trunk
