### ISSUE TITLE
Invalid search bound in sb/visible-table-ranges

### ISSUE THREAD

**Issue by will-henney** [sabof/stripe-buffer#9]
First up, many thanks for `stripe-buffer.el`.  I find it really improves the readability of tabular material in emacs.  Now for my bug report...

I have the following in my emacs config:

```
;; 24 Feb 2014 - Use stripe-buffer in tables
(add-hook 'dired-mode-hook 'turn-on-stripe-buffer-mode)
(add-hook 'tsv-mode-hook 'turn-on-stripe-buffer-mode)
(add-hook 'org-mode-hook 'turn-on-stripe-table-mode)
```

After upgrading to emacs 24.4 I am getting serious performance issues when navigating large org-mode files that have some subtrees folded.   Scrolling is very slow and jerky, and sometimes emacs just hangs for several seconds.  All these problems go away when I turn off `stripe-table-mode`, so I am pretty sure that it is the culprit, but it seems to be an interaction with the folding/unfolding machinery.   

If I fully expand all the headings and _only then_ turn on `stripe-table-mode`, then I don't see so many problems so long as I don't fold any subtrees.   In that case, scrolling performance does still seem to be slightly degraded when a (striped) table is visible on the screen, but not otherwise. 

Also, I occasionally see the following type of error while navigating:

```
sb/visible-table-ranges: Invalid search bound (wrong side of point) [31 times]
Error running timer: (error "Invalid search bound (wrong side of point)")
```

This problem seems to be triggered by using commands like `org-forward-heading-same-level` in a `.org` file that has lots org-mode tables.   Apologies for the lack of a MWE but the problems only manifest in largish files (a few thousand lines with lots of tables).  An example of a file that shows the problem is [here](https://raw.githubusercontent.com/deprecated/orion-tsq/master/orion-t2.org).

**Comment by sabof** [comment]
I'll have a look

**Comment by sabof** [comment]
Have a look at `devel` branch, and let me know if it fixes your issue.
